config/routes.rb
Rails.application.routes.draw do
  resources :beer_clubs
  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"

  resources :beers, :breweries, :users
  resources :ratings, only: %i[index new create destroy]
  resource :session, only: [:new, :create, :destroy]

  root "breweries#index"
end

# see: localhost:3000/rails/info/routes

app/models/beer_club.rb
class BeerClub < ApplicationRecord
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: %i[ show edit update destroy ]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <p>
    <strong>Name:</strong>
    <%= beer_club.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :founded, style: "display: block" %>
    <%= form.number_field :founded %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beer clubs</h1>

<div id="beer_clubs">
  <% @beer_clubs.each do |beer_club| %>
    <%= render beer_club %>
    <p>
      <%= link_to "Show this beer club", beer_club %>
    </p>
  <% end %>
</div>

<%= link_to "New beer club", new_beer_club_path %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beer_club %>

<div>
  <%= link_to "Edit this beer club", edit_beer_club_path(@beer_club) %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>

  <%= button_to "Destroy this beer club", @beer_club, method: :delete %>
</div>