config/routes.rb
Rails.application.routes.draw do
  resources :beer_clubs
  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"

  resources :beers, :breweries, :users
  resources :ratings, only: %i[index new create destroy]
  resource :session, only: [:new, :create, :destroy]

  root "breweries#index"
end

# see: localhost:3000/rails/info/routes

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar">
      <%= link_to "Breweries", breweries_path %>
      <%= link_to "Beers", beers_path %>
      <%= link_to "Ratings", ratings_path %>
      <%= link_to "Users", users_path %>
      |
      <% if current_user %>
        <%= link_to "#{current_user.username}", user_path(current_user) %>
        <%= link_to "Rate a beer", new_rating_path %>
        <%= link_to "Sign out", signout_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "Sign up", signup_path %>
        <%= link_to "Sign in", signin_path %>
      <% end %>
    </div>

    <% if current_user %>
      <p><%= current_user.username %>
        signed in</p>
    <% end %>
    <%= yield %>
  </body>
</html>